# Funding Configuration
# Configure funding options for your project
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# Example funding platforms (uncomment and update as needed):

# GitHub Sponsors
# github: [your-username]

# Open Collective
# open_collective: flexium

# Patreon
# patreon: your-username

# Ko-fi
# ko_fi: your-username

# Buy Me a Coffee
# custom: ['https://www.buymeacoffee.com/your-username']

# Note: This file is optional. Delete it if you don't need funding options.
# Update with your actual funding links when ready.
